name: 'Preprocess yaml'
description: 'Use this action to preprocess yaml files (ex: values)'
inputs:
  file:
    description: 'The file to preprocess'
    required: true
  output:
    description: 'The output file, if not specified, the file will be overwritten'
    required: true
runs:
  using: "composite"
  steps:
    - name: Preprocess yaml
      shell: bash
      run: ${{ github.action_path }}/process.sh ${{ inputs.file }} ${{ inputs.output }}
